services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ksql_zookeeper_data:/var/lib/zookeeper/data
      - ksql_zookeeper_log:/var/lib/zookeeper/log
      - ksql_zookeeper_secrets:/etc/zookeeper/secrets

  kafka:
    image: confluentinc/cp-enterprise-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      -  ksql_kafka_data:/var/lib/kafka/data
      -  ksql_kafka_secrets:/etc/kafka/secrets      

  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    hostname: ksqldb-server
    container_name: ksqldb-server
    command: ["/etc/ksqldb-server/run.sh"]
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - ./files/ksqldb-server:/etc/ksqldb-server

  # docker-compose exec ksqldb-cli  ksql http://ksqldb-server:8088
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
      - kafka
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ./files/ksqldb-cli:/etc/sql
  
#  schema-registry:
#    image: confluentinc/cp-schema-registry:6.0.0
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - '8081:8081'
#      - '31002:31002'
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
#      SCHEMA_REGISTRY_JMX_HOSTNAME: "localhost"
#      SCHEMA_REGISTRY_JMX_PORT: 31002
#    volumes:
#      - ksql_schema_secrets:/etc/schema-registry/secrets

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./files/mysql:/docker-entrypoint-initdb.d
      - ksql_mysql:/var/lib/mysql

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - ksql_redis_data:/data

volumes:
  ksql_zookeeper_data:
  ksql_zookeeper_log:
  ksql_zookeeper_secrets:
  ksql_kafka_data:
  ksql_kafka_secrets:  
#  ksql_schema_secrets:
  ksql_mysql:
#  ksql_redis_data: